# Generated by Django 4.1.2 on 2022-10-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artiste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="enter your first name here(i.e your own name)",
                        max_length=30,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="enter your surname here(i.e your father's name)",
                        max_length=30,
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        help_text="Enter your age in whole number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Artiste",
                "verbose_name_plural": "Artists",
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the name of the song here", max_length=40
                    ),
                ),
                ("date_released", models.DateField(null=True)),
                ("likes", models.PositiveIntegerField()),
                (
                    "artiste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicapp.artiste",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lyrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="enter lyrics here")),
                (
                    "Song_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="musicapp.song"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lyric",
                "verbose_name_plural": "Lyrics",
            },
        ),
    ]
