# Generated by Django 4.1.2 on 2022-10-29 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lyrics",
            old_name="Song_id",
            new_name="song_id",
        ),
    ]
